# This file is the single source of truth for all tensor-grep top-level commands.
# It is read by both the Python Typer application and the Rust native front-door.

KNOWN_COMMANDS = {
    "search",
    "calibrate",
    "upgrade",
    "update",
    "audit-verify",
    "mcp",
    "classify",
    "run",
    "scan",
    "test",
    "new",
    "worker",
    "defs",
    "refs",
    "source",
    "impact",
    "callers",
    "blast-radius",
    "blast-radius-render",
    "blast-radius-plan",
    "edit-plan",
    "context-render",
    "rulesets",
    "audit-history",
    "audit-diff",
    "review-bundle",
    "devices",
    "context",
    "lsp",
    "__gpu-native-stats",
    "__gpu-transfer-bench",
    "__gpu-cuda-graphs",
    "__gpu-oom-probe",
    "map",
    "session",
    "doctor",
    "checkpoint",
}