# `KNOWN_COMMANDS` is the shared top-level command contract read by both the
# Python Typer application and the Rust native front-door. Python-only help
# routing hints live here too, but Rust maintains its own narrower help probe.

PYTHON_FULL_HELP_COMMANDS = {
    "search",
}

KNOWN_COMMANDS = {
    "agent",
    "search",
    "calibrate",
    "upgrade",
    "update",
    "repair-launcher",
    "audit",
    "audit-verify",
    "mcp",
    "classify",
    "run",
    "scan",
    "test",
    "ast-info",
    "new",
    "worker",
    "defs",
    "refs",
    "source",
    "impact",
    "callers",
    "imports",
    "importers",
    "blast-radius",
    "blast-radius-render",
    "blast-radius-plan",
    "edit-plan",
    "context-render",
    "route-test",
    "rulesets",
    "audit-history",
    "audit-diff",
    "review-bundle",
    "evidence",
    "devices",
    "context",
    "lsp",
    "lsp-setup",
    "__gpu-native-stats",
    "__gpu-transfer-bench",
    "__gpu-cuda-graphs",
    "__gpu-oom-probe",
    "map",
    "orient",
    "inventory",
    "docs-coverage",
    "session",
    "doctor",
    "checkpoint",
    "dogfood",
}
