"""Canonical ripgrep parity contract for public search flags.

Each row describes one feature:
- public_flags: the full alias family surfaced to users
- rg_args / tg_args: one canonical executable scenario for that feature
"""

from __future__ import annotations

from typing import Literal, TypedDict


class RGContractRow(TypedDict):
    id: str
    public_flags: tuple[str, ...]
    rg_args: tuple[str, ...]
    tg_args: tuple[str, ...]
    output_mode: Literal[
        "text",
        "count",
        "json",
        "ndjson",
        "files",
        "files_with_matches",
        "files_without_match",
        "help",
        "error",
    ]
    parity_expectation: Literal["exact", "normalized", "unsupported"]
    benchmarkable: bool


RG_CONTRACT_ROWS: tuple[RGContractRow, ...] = (
    {
        "id": "ignore-case",
        "public_flags": ("-i", "--ignore-case"),
        "rg_args": ("--ignore-case",),
        "tg_args": ("--ignore-case",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": True,
    },
    {
        "id": "invert-match",
        "public_flags": ("-v", "--invert-match"),
        "rg_args": ("--invert-match",),
        "tg_args": ("--invert-match",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": True,
    },
    {
        "id": "context",
        "public_flags": ("-C", "--context"),
        "rg_args": ("--context", "2"),
        "tg_args": ("--context", "2"),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": True,
    },
    {
        "id": "after-context",
        "public_flags": ("-A", "--after-context"),
        "rg_args": ("--after-context", "2"),
        "tg_args": ("--after-context", "2"),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": True,
    },
    {
        "id": "before-context",
        "public_flags": ("-B", "--before-context"),
        "rg_args": ("--before-context", "2"),
        "tg_args": ("--before-context", "2"),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": True,
    },
    {
        "id": "glob",
        "public_flags": ("-g", "--glob"),
        "rg_args": ("--glob", "*.py"),
        "tg_args": ("--glob", "*.py"),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": True,
    },
    {
        "id": "files-with-matches",
        "public_flags": ("-l", "--files-with-matches"),
        "rg_args": ("--files-with-matches",),
        "tg_args": ("--files-with-matches",),
        "output_mode": "files_with_matches",
        "parity_expectation": "exact",
        "benchmarkable": True,
    },
    {
        "id": "files-without-match",
        "public_flags": ("--files-without-match",),
        "rg_args": ("--files-without-match",),
        "tg_args": ("--files-without-match",),
        "output_mode": "files_without_match",
        "parity_expectation": "exact",
        "benchmarkable": True,
    },
    {
        "id": "json",
        "public_flags": ("--json",),
        "rg_args": ("--json",),
        "tg_args": ("--json",),
        "output_mode": "json",
        "parity_expectation": "normalized",
        "benchmarkable": False,
    },
    {
        "id": "rg-json-lines",
        "public_flags": ("--format", "--json"),
        "rg_args": ("--json",),
        "tg_args": ("--format", "rg", "--json"),
        "output_mode": "json",
        "parity_expectation": "normalized",
        "benchmarkable": False,
    },
    {
        "id": "ndjson",
        "public_flags": ("--ndjson",),
        "rg_args": ("--ndjson",),
        "tg_args": ("--ndjson",),
        "output_mode": "ndjson",
        "parity_expectation": "normalized",
        "benchmarkable": False,
    },
    {
        "id": "fixed-strings",
        "public_flags": ("-F", "--fixed-strings"),
        "rg_args": ("--fixed-strings",),
        "tg_args": ("--fixed-strings",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": True,
    },
    {
        "id": "word-regexp",
        "public_flags": ("-w", "--word-regexp"),
        "rg_args": ("--word-regexp",),
        "tg_args": ("--word-regexp",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": True,
    },
    {
        "id": "max-count",
        "public_flags": ("-m", "--max-count"),
        "rg_args": ("--max-count", "10"),
        "tg_args": ("--max-count", "10"),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": True,
    },
    {
        "id": "type",
        "public_flags": ("-t", "--type"),
        "rg_args": ("--type", "py"),
        "tg_args": ("--type", "py"),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": True,
    },
    {
        "id": "hidden",
        "public_flags": ("-.", "--hidden"),
        "rg_args": ("--hidden",),
        "tg_args": ("--hidden",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": True,
    },
    {
        "id": "no-hidden",
        "public_flags": ("--no-hidden",),
        "rg_args": ("--no-hidden",),
        "tg_args": ("--no-hidden",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": False,
    },
    {
        "id": "follow",
        "public_flags": ("-L", "--follow"),
        "rg_args": ("--follow",),
        "tg_args": ("--follow",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": True,
    },
    {
        "id": "smart-case",
        "public_flags": ("-S", "--smart-case"),
        "rg_args": ("--smart-case",),
        "tg_args": ("--smart-case",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": True,
    },
    {
        "id": "line-number",
        "public_flags": ("-n", "--line-number"),
        "rg_args": ("--line-number",),
        "tg_args": ("--line-number",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": True,
    },
    {
        "id": "no-line-number",
        "public_flags": ("-N", "--no-line-number"),
        "rg_args": ("--no-line-number",),
        "tg_args": ("--no-line-number",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": True,
    },
    {
        "id": "column",
        "public_flags": ("--column",),
        "rg_args": ("--column",),
        "tg_args": ("--column",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": True,
    },
    {
        "id": "column-disabled",
        "public_flags": ("--column", "--no-column"),
        "rg_args": ("--column", "--no-column"),
        "tg_args": ("--column", "--no-column"),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": False,
    },
    {
        "id": "count",
        "public_flags": ("-c", "--count"),
        "rg_args": ("--count",),
        "tg_args": ("--count",),
        "output_mode": "count",
        "parity_expectation": "exact",
        "benchmarkable": True,
    },
    {
        "id": "count-matches",
        "public_flags": ("--count-matches",),
        "rg_args": ("--count-matches",),
        "tg_args": ("--count-matches",),
        "output_mode": "count",
        "parity_expectation": "exact",
        "benchmarkable": True,
    },
    {
        "id": "text",
        "public_flags": ("-a", "--text"),
        "rg_args": ("--text",),
        "tg_args": ("--text",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": True,
    },
    {
        "id": "passthru",
        "public_flags": ("--passthru",),
        "rg_args": ("--passthru",),
        "tg_args": ("--passthru",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": False,
    },
    {
        "id": "pcre2-unicode",
        "public_flags": ("--pcre2-unicode",),
        "rg_args": ("--pcre2-unicode",),
        "tg_args": ("--pcre2-unicode",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": False,
    },
    {
        "id": "ignore",
        "public_flags": ("--ignore",),
        "rg_args": ("--ignore",),
        "tg_args": ("--ignore",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": False,
    },
    {
        "id": "messages",
        "public_flags": ("--messages",),
        "rg_args": ("--messages",),
        "tg_args": ("--messages",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": False,
    },
    {
        "id": "require-git",
        "public_flags": ("--require-git",),
        "rg_args": ("--require-git",),
        "tg_args": ("--require-git",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": False,
    },
    {
        "id": "no-ignore-dot",
        "public_flags": ("--no-ignore-dot",),
        "rg_args": ("--no-ignore-dot",),
        "tg_args": ("--no-ignore-dot",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": False,
    },
    {
        "id": "no-ignore-exclude",
        "public_flags": ("--no-ignore-exclude",),
        "rg_args": ("--no-ignore-exclude",),
        "tg_args": ("--no-ignore-exclude",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": False,
    },
    {
        "id": "no-ignore-files",
        "public_flags": ("--no-ignore-files",),
        "rg_args": ("--no-ignore-files",),
        "tg_args": ("--no-ignore-files",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": False,
    },
    {
        "id": "no-ignore-global",
        "public_flags": ("--no-ignore-global",),
        "rg_args": ("--no-ignore-global",),
        "tg_args": ("--no-ignore-global",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": False,
    },
    {
        "id": "no-ignore-parent",
        "public_flags": ("--no-ignore-parent",),
        "rg_args": ("--no-ignore-parent",),
        "tg_args": ("--no-ignore-parent",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": False,
    },
    {
        "id": "no-config",
        "public_flags": ("--no-config",),
        "rg_args": ("--no-config",),
        "tg_args": ("--no-config",),
        "output_mode": "text",
        "parity_expectation": "exact",
        "benchmarkable": False,
    },
    {
        "id": "type-list",
        "public_flags": ("--type-list",),
        "rg_args": ("--type-list",),
        "tg_args": ("--type-list",),
        "output_mode": "help",
        "parity_expectation": "normalized",
        "benchmarkable": False,
    },
    {
        "id": "pcre2-version",
        "public_flags": ("--pcre2-version",),
        "rg_args": ("--pcre2-version",),
        "tg_args": ("--pcre2-version",),
        "output_mode": "help",
        "parity_expectation": "normalized",
        "benchmarkable": False,
    },
)


PUBLIC_SEARCH_HELP_FLAGS: tuple[str, ...] = tuple(
    dict.fromkeys(flag for row in RG_CONTRACT_ROWS for flag in row["public_flags"])
)
