PackageIdentifier: oimiragieo.tensor-grep
PackageVersion: 1.13.33
InstallerType: portable
UpgradeBehavior: install
Commands:
  - tg
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/oimiragieo/tensor-grep/releases/download/v1.13.33/tg-windows-amd64-cpu.exe
    InstallerSha256: 2D9CD666A2140162CF640B385DCFC97A96DEFE93D1665C929229D185793C1589
    Scope: user
ManifestType: installer
ManifestVersion: 1.6.0
