"""A RATCHET over the silent-filesystem-loss class in the Python sources.

THE CLASS: a loop walks filesystem entries and accumulates them into a collection that is
later reported as a result. One entry raises ``OSError`` (permission denied, a vanished file,
a disconnected share). A broad ``except`` swallows it and ``continue``s. The loop finishes,
the collection is SMALLER than the universe it claims to describe, and the command exits 0
with no marker. The caller -- almost always an AI agent -- concludes "no callers, safe to
delete" from a result set that was silently truncated.

That is the same defect the Rust-side ratchet pins for directory walks
(``test_native_walk_error_ratchet.py``, task #276). This file is its Python counterpart:
the codebase had a machine-checked census for one language and hand-enumeration for the
other, which is why the unreadable-path family (#276, #283, #284, #286, #288, #291) was
found one site at a time across a dozen separate PRs.

WHAT THIS DOES *NOT* CLAIM. A site in the census is not automatically a bug. Plenty of
best-effort loops are correct to skip an unreadable entry -- a heuristic seed list, an
optional cache probe. The census is the POPULATION that contains the defects, not the defect
list. Its job is the invariant: *the number of silent-loss sites never increases.* Auditing
a site and fixing it lowers the number; adding one without thinking about disclosure raises
it and turns CI red.

HOW A SITE GETS FIXED. Thread a ``_UnreadablePathFlag`` (see ``repo_map.py``) through the
loop, ``record(exc)`` in the handler, and have the caller disclose ``unreadable_paths``
alongside its result -- the shape #276 established and #767/#768/#769/#770 wired into
inventory, docs-coverage, the session snapshot and the validation plan. Then LOWER the count
here in the same PR.

House rule this implements: "model the class, don't enumerate the cases". Round N+1 finding
another instance of a defect family means the answer is an invariant, not another reviewer.

WHERE THAT RULE STOPS -- a near miss worth keeping (#292, 2026-07-26). Several audited-benign
sites share a shape: the handler only ASSIGNS a fallback and lets the loop continue, so nothing
is skipped (``resolved = candidate`` in the doctor PATH scans, ``_nearby_session_roots``). It is
tempting to teach the detector that shape and drop ~20 sites of noise in one edit.

Measuring the shape's distribution before encoding it showed why that would be a disaster:
``checkpoint_store``'s undo commit phase matched it too -- ``removed_bytes = None`` followed by an
``unlink()`` that destroys a file the revert can no longer restore. That was task #297, the most
severe defect this campaign found. A "benign fallback" rule would have excused it FOREVER, in the
exact file where it mattered most.

The lesson generalises: encode a shape only when it is *structurally* incapable of hiding a loss
(a handler that exits the process; one whose accumulator feeds a later ``raise``). "The handler
looks harmless" is not that. Whether a fallback is safe depends on what the loop DOES with the
fallback value afterwards, which is a semantic question this detector deliberately does not try
to answer. Audit those sites and record the verdict instead -- see CONTRACTS.md section 0.
"""

from __future__ import annotations

import ast
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
PY_SRC = REPO_ROOT / "src" / "tensor_grep"

# Filesystem calls whose failure means "this entry is missing from the result".
_FS_CALLS = frozenset(
    {
        "stat", "lstat", "open", "read_text", "read_bytes", "iterdir", "scandir",
        "walk", "resolve", "exists", "is_file", "is_dir", "is_symlink", "glob",
        "rglob", "listdir", "samefile",
    }
)  # fmt: skip

# A handler that does any of these has DISCLOSED the loss, so it is not silent.
_DISCLOSING_CALLS = frozenset({"record", "warning", "error", "exception", "critical"})

# Methods that accumulate into a collection the loop will hand back to a caller.
_ACCUMULATORS = frozenset({"append", "add", "update", "extend", "setdefault"})

# Exception types broad enough to swallow a filesystem failure. "BARE" is `except:`.
_BROAD_EXCEPTIONS = frozenset({"BARE", "OSError", "Exception", "EnvironmentError", "IOError"})

# MECHANICAL CENSUS -- generated by running this module's own detector, never from
# recollection. (A hand count of the unreadable-path family said "4 remaining repo_map
# sites"; the detector found 8 in that file alone. That gap is the whole reason this is
# machine-checked instead of prose.)
#
# file name -> number of silent-loss-in-an-accumulating-loop sites currently present.
#
# Started at 53 across 12 files. `docs_coverage.py` (2) and `inventory.py` (1) were audited and
# fixed in this same PR -- both were real gaps left by #767/#768, which wired the WALK but not the
# per-file read/stat loops -- so they are absent below rather than listed at zero.
KNOWN_SILENT_LOSS_SITES: dict[str, int] = {
    # 18 -> 15 by TWO INDEPENDENT fixes that landed in parallel; this file has been burned once
    # already by a hand count, so the arithmetic is spelled out:
    #   -2 by #299 -- the regex-ruleset read loop now records into the scan payload. It counts for
    #     TWO because the handler sits inside nested accumulating loops (`for rule` -> `for
    #     current_file`) and the detector visits it once per enclosing loop, so a single fix can
    #     move this number by more than one. Not a miscount: the invariant is "never rises".
    #   -1 by the `-f`/`--file` pattern-file read -- it already failed loud with exit 2 (the
    #     Backend Fail-Closed Contract), but the handler calls `_exit_search_error` rather than
    #     raising inline, so the detector read a terminating branch as silence.
    #
    # AUDITED #292: the remaining sites fall into three families, all accepted. Recording the
    # FAMILIES rather than a per-site list, because a line-numbered enumeration rots on the next
    # edit.
    #   FALLBACK-ASSIGN (launcher scan, doctor PATH scans) -- the handler assigns an unresolved-
    #     path fallback and the loop CONTINUES with it. Nothing is skipped.
    #   OUTPUT-BUCKET (launcher cleanup) -- `failed.append(...)`, rendered into the command's own
    #     output. That IS the disclosure; the detector cannot see it because it is resolved
    #     outside the handler (same shape as session_store:589).
    #   BROAD-SCAN GUARDRAIL -- main.py's own copies of the `scan_guardrails` refusal heuristic
    #     (#154/#158 siblings). An OSError only means a huge scan is not refused; the scan that
    #     follows discloses its own incompleteness.
    # CAUTION for whoever drains this next: FALLBACK-ASSIGN is NOT safe as a general rule -- it
    # also matched checkpoint_store's #297 data-loss. See the header note on where the
    # "model the class" rule stops.
    # 15 -> 6 + 5 + 4 by the cli/main.py SPLIT (2026-08-20,
    # docs/design/2026-08-19-split-floor-escape.md). NOT a fix and NOT a regression: nine of the
    # fifteen handlers moved, byte-identical, into two extracted siblings, and this census is
    # keyed by FILE. The arithmetic is spelled out because this file has been burned by a hand
    # count before, and because the invariant that matters here is CONSERVATION, not each
    # per-file number:
    #     main.py 6  +  doctor_report.py 5  +  windows_launcher.py 4  =  15, the old pin exactly.
    # Measured, not asserted: `_census()` over the six modules (main.py plus its five children)
    # totals 15 and the other three children contribute 0. Every one of the nine relocated sites
    # is in the already-audited families recorded above -- FALLBACK-ASSIGN (the doctor PATH scans
    # and the launcher scan) and OUTPUT-BUCKET (the launcher cleanup's `failed.append(...)`) --
    # so the audit that accepted them still applies; moving a file does not re-open it.
    # Retire these two entries together with main.py's when that module is drained.
    # RELOCATION 2026-08-21: `generated_scan_dir_names` moved main.py -> scan_guardrails.py
    # (paying for the missing-path guard under the file-size ratchet) and took its two
    # `except OSError` sites with it. Measured: main.py 6->4, scan_guardrails.py 5->7,
    # TOTAL 41 -> 41 unchanged. Re-pinned because the sites MOVED, not because any were added --
    # a growing total must be hardened or disposed, never re-pinned.
    "main.py": 4,
    "doctor_report.py": 5,
    "windows_launcher.py": 4,
    # 10 -> 6 by #297: three real fixes (the undo commit phase destroying a file whose bytes it
    # had failed to capture, so the revert could not restore it) plus one FALSE POSITIVE that the
    # detector no longer reports -- the undo pre-flight accumulates into `missing` and then raises
    # on it, which is disclosure, not loss.
    #
    # 6 -> 7 by #308, and this one is a DETECTOR LIMITATION, not a new loss. The new site is
    # `_paths_modified_since_checkpoint`'s OSError arm, which appends the unstattable path to
    # `unchecked` and RETURNS it; undo then surfaces it as `divergence_unchecked_paths`, so the
    # caller is told exactly which files divergence could not be decided for. `_is_silent`
    # recognises accumulate-then-RAISE as disclosure (that is the #297 false positive above) but
    # has no notion of accumulate-then-RETURN-and-emit, so it still counts this handler.
    #
    # Raising the ceiling is the deliberate choice over widening `_is_silent`: teaching the
    # detector to treat "appends to something the function returns" as disclosure would also
    # excuse every handler that appends to a list nobody ever reads, which is precisely the shape
    # it exists to catch. Filed as a task to model the return-and-disclose shape properly rather
    # than by loosening the predicate.
    "checkpoint_store.py": 6,
    # AUDITED #292, all 8 accepted. The LSP legs (`_external_definitions` :15585,
    # `_external_references` :15693) skip a symbol whose LSP request failed, which lowers
    # `lsp_count` -- and `_provider_agreement` (:15258-15281) turns `native_count > lsp_count`
    # into `diverged` rather than a clean `lsp-only` proof. The loss reaches the caller through
    # that stamp; the comment at :15268 traces it to the v1.20.0 dogfood where `tg refs
    # --provider lsp` returned 2 of 14 marked authoritative. `:15713` is a different shape: a
    # failed `read_text` degrades the SNIPPET to the symbol name but still appends the reference,
    # so nothing is lost. CAVEAT: this verdict is from reading the code, not from a test that
    # observes the stamp flip -- proving it needs a live LSP server or heavy mocking.
    "repo_map.py": 8,
    # AUDITED #292, all 5 accepted. These gate the broad-scan REFUSAL heuristic, not an answer:
    # an OSError only means a huge scan is not refused, and the scan that follows discloses its
    # own incompleteness. main.py carries its own copies of the same family (#154/#158 siblings).
    # They stay pinned so a NEW one still trips the ratchet.
    "scan_guardrails.py": 7,
    # codemap.py drained to 0 by #296 (was 3): the tracked-file filter, the folder census and the
    # freshness digest now record into a post-walk accumulator that reaches `coverage.partial`.
    # Absent rather than pinned at 0 -- an entry at 0 and no entry are equivalent to both ratchet
    # arms, and the absence is what makes a re-introduction show up as a NEW file.
    # AUDITED #292, both session_store entries accepted, and they are two DIFFERENT non-defects:
    #   `_nearby_session_roots` :406 -- `resolved = candidate` is a FALLBACK, not a skip. The
    #     candidate stays in the loop; nothing is dropped at the handler.
    #   `_stale_changeset` :589 -- the #286 fix itself. It routes to a dedicated `indeterminate`
    #     bucket (plus `indeterminate_kinds`), which IS the disclosure: an unreadable file is
    #     deliberately left out of removed/changed/added rather than being called a deletion.
    # The second is a shape the detector structurally cannot see -- disclosure by routing to a
    # separate OUTPUT BUCKET, resolved outside the handler. Not worth widening the rule for:
    # "appends to a collection that is also returned" would match almost every real accumulator
    # and blind the detector. Recorded here instead, per CONTRACTS.md section 0.
    # RELOCATION, not a new site, and the arithmetic is spelled out because this repo's rule is
    # that GROWTH must be hardened while RELOCATION may re-pin ONLY on proof the total is
    # unchanged. Measured before and after the 2026-08-23 split of project-root resolution into
    # `session_root.py`:
    #     session_store.py  2 -> 1     (the `_nearby_session_roots` handler moved out)
    #     session_root.py   absent -> 1 (the same handler, byte-identical, at its new home)
    #     TOTAL             2 -> 2
    # session_store's pin is LOWERED in the same change, because this ratchet fails on a pin left
    # above the real count -- a pin above the count accepts a range, and a range is where the next
    # regression hides.
    #
    # The other handler in `session_root.py` (`_shared_territory_roots`) is deliberately NOT a
    # silent-loss site: it degrades an unresolvable candidate to its unresolved path instead of
    # dropping it, because that set is a DENY set and a dropped entry fails OPEN.
    "session_store.py": 1,
    "session_root.py": 1,
    "ledger_store.py": 1,
    "runtime_paths.py": 1,
    "session_daemon.py": 1,
    # AUDITED F7 Task 11 wave 3 (lang_c_cpp_include.py): two fail-closed confirmation
    # helpers, not a completeness-claiming result set.
    #   resolve_include_target -- `except OSError: continue` while resolving include search
    #     roots into the `seen` dedup set. An unreadable root is skipped; the function returns
    #     None (unresolved) rather than fabricating a path. The caller elevates a caller edge
    #     to the include-confirmed band only on a successful resolve -- silence here is the
    #     fail-closed contract, not a truncated answer.
    #   file_includes_definition -- same shape over same-stem header siblings (`acceptable.add`).
    #     An unreadable sibling is omitted from the match set; the predicate returns False
    #     (do not elevate) rather than claiming the include graph is complete.
    # No `_UnreadablePathFlag` path: this module deliberately does not import `repo_map`
    # (cycle), and a boolean confirmation surface has no `unreadable_paths` consumer.
    "lang_c_cpp_include.py": 2,
}


def _called_names(node: ast.AST) -> set[str]:
    """Every attribute/function name called anywhere under ``node``."""
    return {
        name
        for child in ast.walk(node)
        if isinstance(child, ast.Call)
        and (name := getattr(child.func, "attr", None) or getattr(child.func, "id", None))
    }


def _caught_names(handler: ast.ExceptHandler) -> set[str]:
    exc_type = handler.type
    if exc_type is None:
        return {"BARE"}
    parts = exc_type.elts if isinstance(exc_type, ast.Tuple) else [exc_type]
    return {getattr(p, "attr", None) or getattr(p, "id", None) or "?" for p in parts}


def _terminates(handler: ast.ExceptHandler) -> bool:
    """True when the handler hands control to something that ends the command.

    ``sys.exit`` and this codebase's ``_exit_*`` helpers (e.g. ``_exit_search_error``) raise
    ``SystemExit`` internally, so nothing downstream ever sees a truncated result. The AST shows
    only a call, which read as silence and produced FALSE POSITIVES -- `-f` pattern-file reads
    (main.py) are the clearest case: they already fail loud with exit 2 per the Backend
    Fail-Closed Contract, and the census still counted them.
    """
    return any(
        name == "exit" or name.startswith("_exit_") or name.startswith("exit_")
        for name in _called_names(handler)
    )


def _raised_names(func: ast.AST) -> set[str]:
    """Names mentioned inside any ``raise`` in ``func``.

    Catches the accumulate-then-raise shape: the handler appends the failure to a list and the
    function raises on that list once the loop finishes (``checkpoint_store``'s undo pre-flight
    builds ``missing`` and then raises ``CheckpointCorruptError(..., missing_files=missing)``).
    Handler-local inspection cannot see that, so it counted a DISCLOSURE accumulator as loss.
    """
    names: set[str] = set()
    for node in ast.walk(func):
        if isinstance(node, ast.Raise):
            names |= {n.id for n in ast.walk(node) if isinstance(n, ast.Name)}
    return names


def _is_silent(handler: ast.ExceptHandler, raised_names: set[str]) -> bool:
    """True when the handler neither re-raises, records, terminates, nor feeds a later raise."""
    if any(isinstance(n, ast.Raise) for n in ast.walk(handler)):
        return False
    if _terminates(handler):
        return False
    if _called_names(handler) & _DISCLOSING_CALLS:
        return False
    # `missing.append(rel)` where the enclosing function later raises using `missing`.
    accumulated_into = {
        node.func.value.id
        for node in ast.walk(handler)
        if isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and node.func.attr in _ACCUMULATORS
        and isinstance(node.func.value, ast.Name)
    }
    return not (accumulated_into & raised_names)


def _returned_names(func: ast.AST) -> set[str]:
    """Names mentioned inside any ``return`` in ``func`` (task #807).

    The accumulate-then-RETURN sibling of ``_raised_names``. A handler that appends the failure
    to a list the function RETURNS has disclosed it just as surely as one that raises on it --
    the caller receives the record either way. `_paths_modified_since_checkpoint` is the live
    case: its ``except OSError`` appends to ``unchecked`` and the function returns
    ``(sorted(diverged), sorted(unchecked))``, so undo can report which paths it could not check.

    Without this the census counted that DISCLOSURE as loss, which was not merely a false
    positive -- it made the ratchet unable to DISCRIMINATE at that site. The count was identical
    with the disclosure and with a bare ``continue``, so re-introducing the silent drop kept the
    gate green. Proven by mutation before this was written: the ceiling of 7 protected nothing
    there.

    Deliberately narrow. It is NOT "appends to any list": the accumulator must reach a value the
    function actually hands back. Widening it to any append would excuse every handler stuffing a
    list nobody reads, which is exactly the loss this census exists to find -- and is why the
    ceiling was raised to 7 rather than the detector loosened at the time.
    """
    names: set[str] = set()
    for node in ast.walk(func):
        if isinstance(node, ast.Return) and node.value is not None:
            names |= {n.id for n in ast.walk(node.value) if isinstance(n, ast.Name)}
    return names


def _enclosing_raised_names(tree: ast.AST) -> dict[int, set[str]]:
    """Map each loop node's id() to the DISCLOSED names of the function that contains it.

    "Disclosed" = raised on OR returned. Both hand the record to the caller; a handler feeding
    either one is reporting the failure, not swallowing it.
    """
    mapping: dict[int, set[str]] = {}
    for func in ast.walk(tree):
        if not isinstance(func, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        disclosed = _raised_names(func) | _returned_names(func)
        if not disclosed:
            continue
        for node in ast.walk(func):
            if isinstance(node, (ast.For, ast.While, ast.AsyncFor)):
                mapping[id(node)] = mapping.get(id(node), set()) | disclosed
    return mapping


def _silent_loss_lines(source: str) -> list[int]:
    """Line numbers of silent-loss sites in ``source``.

    A site is: a broad ``except`` that discloses nothing -- no re-raise, no log/record, no exit,
    and no accumulator the enclosing function later raises on -- guarding a ``try`` body that
    touches the filesystem, nested inside a loop whose body accumulates or yields.
    """
    tree = ast.parse(source)
    raised_by_loop = _enclosing_raised_names(tree)
    found: list[int] = []
    for loop in ast.walk(tree):
        if not isinstance(loop, (ast.For, ast.While, ast.AsyncFor)):
            continue
        accumulates = bool(_called_names(loop) & _ACCUMULATORS) or any(
            isinstance(n, (ast.Yield, ast.YieldFrom)) for n in ast.walk(loop)
        )
        if not accumulates:
            continue
        for try_node in ast.walk(loop):
            if not isinstance(try_node, ast.Try):
                continue
            # Only the try BODY counts: an fs call inside the handler itself (a cleanup
            # probe) does not mean the guarded operation was a filesystem read.
            if not any(_called_names(stmt) & _FS_CALLS for stmt in try_node.body):
                continue
            raised = raised_by_loop.get(id(loop), set())
            found.extend(
                h.lineno
                for h in try_node.handlers
                if (_caught_names(h) & _BROAD_EXCEPTIONS) and _is_silent(h, raised)
            )
    return found


def _census() -> dict[str, int]:
    """Count silent-loss sites per Python source file under ``src/tensor_grep``."""
    found: dict[str, int] = {}
    for path in sorted(PY_SRC.rglob("*.py")):
        hits = _silent_loss_lines(path.read_text(encoding="utf-8", errors="replace"))
        if hits:
            found[path.name] = len(hits)
    return found


@pytest.mark.skipif(not PY_SRC.is_dir(), reason="src/tensor_grep absent")
def test_no_new_files_start_losing_entries_silently() -> None:
    """A file not in the census must not introduce the idiom.

    This is the arm that bites on new code: a fresh ``except OSError: continue`` inside a
    result-building loop, in a file nobody has audited, is exactly how a command starts
    reporting success over a smaller universe.
    """
    unexpected = sorted(set(_census()) - set(KNOWN_SILENT_LOSS_SITES))
    assert not unexpected, (
        "these files newly swallow a filesystem error inside a loop that accumulates a "
        f"reported result, so a truncated result looks complete: {unexpected}. Thread an "
        "_UnreadablePathFlag through the loop and disclose `unreadable_paths` (see "
        "inventory.py / docs_coverage.py for the shape), or add the file to "
        "KNOWN_SILENT_LOSS_SITES with a reason if the loop genuinely makes no completeness "
        "claim."
    )


@pytest.mark.skipif(not PY_SRC.is_dir(), reason="src/tensor_grep absent")
def test_known_silent_loss_sites_never_grow() -> None:
    """Each audited file's count may FALL (a fix) but never RISE (a regression)."""
    census = _census()
    grew = {
        name: (census.get(name, 0), expected)
        for name, expected in KNOWN_SILENT_LOSS_SITES.items()
        if census.get(name, 0) > expected
    }
    assert not grew, (
        "the silent-loss count ROSE in these files (actual, allowed): "
        f"{grew}. Every added site is a new way for an incomplete result to report success."
    )

    shrank = {
        name: (census.get(name, 0), expected)
        for name, expected in KNOWN_SILENT_LOSS_SITES.items()
        if census.get(name, 0) < expected
    }
    assert not shrank, (
        "sites were FIXED but the ratchet was not lowered (actual, recorded): "
        f"{shrank}. Update KNOWN_SILENT_LOSS_SITES to the new counts so the ratchet keeps "
        "its teeth -- leaving it high would let a future regression slip back in unnoticed."
    )


@pytest.mark.skipif(not PY_SRC.is_dir(), reason="src/tensor_grep absent")
def test_the_detector_actually_discriminates() -> None:
    """ORACLE CHECK -- prove the detector bites before trusting either arm above.

    Without this, a detector that matched nothing would find zero sites everywhere, both
    ratchet arms would pass, and this file would silently certify a codebase it never
    inspected. A check that passes when the thing it guards is broken is not a check.
    (Verification-oracle family, form: the FIXTURE never applied.)

    The negative arms matter as much as the positive one: if a DISCLOSED handler still
    counted, fixing a site would not lower the number and the ratchet could never reach zero.
    """
    silent = """
for path in paths:
    try:
        out.append(path.stat().st_size)
    except OSError:
        continue
"""
    assert _silent_loss_lines(silent) == [5], "detector missed a plain silent-loss site"

    recorded = """
for path in paths:
    try:
        out.append(path.stat().st_size)
    except OSError as exc:
        unreadable.record(exc)
        continue
"""
    assert not _silent_loss_lines(recorded), "a handler that RECORDS must not count as silent"

    reraised = """
for path in paths:
    try:
        out.append(path.stat().st_size)
    except OSError as exc:
        raise BackendExecutionError(str(exc)) from exc
"""
    assert not _silent_loss_lines(reraised), "a handler that RE-RAISES must not count as silent"

    narrow = """
for path in paths:
    try:
        out.append(path.stat().st_size)
    except UnicodeDecodeError:
        continue
"""
    assert not _silent_loss_lines(narrow), (
        "a NARROW exception unrelated to filesystem availability must not count -- widening "
        "the detector to it would bury the real signal in noise"
    )

    no_claim = """
for path in paths:
    try:
        probe(path.stat())
    except OSError:
        continue
"""
    assert not _silent_loss_lines(no_claim), (
        "a loop that accumulates NOTHING makes no completeness claim and must not count"
    )

    # The two shapes the detector learned to forgive. Each needs BOTH arms: teaching it that
    # `_exit_*` and accumulate-then-raise are disclosure is exactly how a detector starts
    # under-reporting, so the near-miss must still count.
    terminates = """
for path in paths:
    try:
        out.append(path.stat().st_size)
    except OSError as exc:
        _exit_search_error("read_error", str(exc), json_mode=False, exit_code=2)
"""
    assert not _silent_loss_lines(terminates), (
        "a handler that EXITS the command cannot hand anyone a truncated result"
    )

    accumulate_then_raise = """
def check(paths):
    missing = []
    for path in paths:
        try:
            path.stat()
        except OSError:
            missing.append(path)
    if missing:
        raise CheckpointCorruptError("corrupt", missing_files=missing)
"""
    assert not _silent_loss_lines(accumulate_then_raise), (
        "appending to a list the function then RAISES on is disclosure, not loss"
    )

    accumulate_never_raised = """
def check(paths):
    missing = []
    kept = []
    for path in paths:
        try:
            kept.append(path.stat().st_size)
        except OSError:
            missing.append(path)
    if not kept:
        raise ValueError("empty")
    return kept
"""
    assert _silent_loss_lines(accumulate_never_raised), (
        "NEAR MISS: the function raises, but on `kept` -- `missing` is collected and thrown "
        "away, so the loss IS silent. If this stops counting, the raise-name check has "
        "widened into 'any raise anywhere excuses the whole function'."
    )

    # And the census must be non-empty: if it were, the two ratchet arms would pass
    # vacuously no matter how much the real code drops on the floor.
    assert _census(), (
        "the census found ZERO silent-loss sites. Either every site was fixed (then empty "
        "KNOWN_SILENT_LOSS_SITES and delete this assertion) or the detector broke."
    )
