"""Task #276 slice 2c -- a RATCHET over the walk-error-discard class in the Rust sources.

THE CLASS: a directory walk written as `.filter_map(|e| e.ok())` silently DISCARDS every
per-entry error. A permission-denied subdirectory, a broken symlink, or an I/O fault vanishes:
the walk yields fewer files and the command still exits 0 with no marker in the envelope. That
is the #276 defect -- "reports success while the result is incomplete".

WHY A RATCHET AND NOT A FIX. The fix is Rust and this repo's dev box is CPU-constrained: the
agent maintaining these files cannot run `cargo build`/`check`/`clippy`, so CI is the only
oracle for a Rust change. Rather than ship 10 unverifiable edits at once, this test does the
part that IS locally verifiable and permanently enforced -- it pins the census so the class
cannot GROW while the individual sites are fixed one CI-verified slice at a time.

This follows the house rule "model the class, don't enumerate the cases": round N+1 finding
another instance of a defect family means the answer is an invariant, not another reviewer.
The invariant here is *the number of error-discarding walks never increases*.

ALREADY FIXED, deliberately absent from the census below (they now report the error instead of
dropping it -- see #280): `native_search.rs` streaming walker, `gpu_native.rs` walker.

To fix a site: replace `.filter_map(|e| e.ok())` with an arm that keeps the Ok entries AND
surfaces the Err ones (count them, or route them to the same reporting path #280 used), then
LOWER the number here in the same PR. Lowering is expected; raising requires deleting this
test, which is the point.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
RUST_SRC = REPO_ROOT / "rust_core" / "src"

# The error-discarding walk idiom, in both spellings the codebase uses.
_DISCARD_PATTERN = re.compile(r"\.filter_map\(\s*(?:\|e\|\s*e\.ok\(\)|Result::ok)\s*\)")

# MECHANICAL CENSUS -- generated by grepping, never from recollection. (An earlier note in the
# task tracker said "6 more sites"; the actual grep found 10. That gap is exactly why this
# census is machine-checked instead of prose.)
#
# file name -> number of error-discarding walks currently present.
KNOWN_DISCARD_SITES: dict[str, int] = {
    "backend_ast_workflow.rs": 3,
    # 6 -> 4: this PR's `replace_in_place` hardening removed two error-discarding walks in
    # directory mode (the `WalkDir::new(...).filter_map(|e| e.ok())` plus the `let _ = ...`
    # per-child replace), so walk failures and per-child write failures now propagate as
    # `Err(...)` instead of letting a partial rewrite report success. Lowered here in the SAME
    # PR that fixed them: the ratchet's own failure message is explicit that leaving the number
    # high "would let a future regression slip back in unnoticed" -- a ratchet that is not
    # re-tightened after a fix has no teeth for the sites that remain.
    # 4 -> 0: audit-H1 fix (`backend_cpu.rs` search_with_paths + count paths) replaced the
    # `filter_map(|e| e.ok())` walk idiom with `collect::<Result<Vec<_>,_>>()?`, so every walk
    # error now propagates (rust_backend.py -> BackendExecutionError -> visible CPU fallback)
    # instead of silently dropping entries. Lowered here in the SAME PR -- a ratchet that is
    # not re-tightened after a fix has no teeth for the sites that remain.
    "backend_cpu.rs": 0,
    "index.rs": 1,
}


def _census() -> dict[str, int]:
    """Count error-discarding walk sites per Rust source file."""
    found: dict[str, int] = {}
    for path in sorted(RUST_SRC.glob("*.rs")):
        hits = len(_DISCARD_PATTERN.findall(path.read_text(encoding="utf-8", errors="replace")))
        if hits:
            found[path.name] = hits
    return found


@pytest.mark.skipif(not RUST_SRC.is_dir(), reason="rust_core/src absent (sdist-only checkout)")
def test_no_new_files_start_discarding_walk_errors() -> None:
    """A file not in the census must not introduce the idiom.

    This is the arm that actually bites on new code: a fresh `.filter_map(|e| e.ok())` in a
    file nobody has audited is precisely how #264/#266/#267/#269 became one defect wearing
    four faces.
    """
    unexpected = sorted(set(_census()) - set(KNOWN_DISCARD_SITES))
    assert not unexpected, (
        "these Rust files newly discard per-entry walk errors via `.filter_map(|e| e.ok())`, "
        "which makes a truncated walk look like a complete one (task #276): "
        f"{unexpected}. Surface the Err arm instead of dropping it -- see the #280 sites in "
        "native_search.rs for the shape -- or add the file to KNOWN_DISCARD_SITES with a "
        "reason if it genuinely cannot fail."
    )


@pytest.mark.skipif(not RUST_SRC.is_dir(), reason="rust_core/src absent (sdist-only checkout)")
def test_known_discard_sites_never_grow() -> None:
    """Each audited file's count may FALL (a fix) but never RISE (a regression)."""
    census = _census()
    grew = {
        name: (census.get(name, 0), expected)
        for name, expected in KNOWN_DISCARD_SITES.items()
        if census.get(name, 0) > expected
    }
    assert not grew, (
        "the walk-error-discard count ROSE in these files (actual, allowed): "
        f"{grew}. Every added `.filter_map(|e| e.ok())` is a new way for a truncated walk to "
        "report success (task #276)."
    )

    shrank = {
        name: (census.get(name, 0), expected)
        for name, expected in KNOWN_DISCARD_SITES.items()
        if census.get(name, 0) < expected
    }
    assert not shrank, (
        "sites were FIXED but the ratchet was not lowered (actual, recorded): "
        f"{shrank}. Update KNOWN_DISCARD_SITES in this file to the new counts so the ratchet "
        "keeps its teeth -- leaving it high would let a future regression slip back in "
        "unnoticed."
    )


@pytest.mark.skipif(not RUST_SRC.is_dir(), reason="rust_core/src absent (sdist-only checkout)")
def test_the_detector_actually_matches_the_idiom() -> None:
    """ORACLE CHECK -- prove the regex bites before trusting either arm above.

    Without this, a typo'd pattern would find zero hits everywhere, both tests would pass, and
    the ratchet would silently certify a codebase it never actually inspected. A check that
    passes when the thing it guards is broken is not a check. (Verification-oracle family,
    form: the FIXTURE never applied.)
    """
    assert _DISCARD_PATTERN.search("for e in walker.filter_map(|e| e.ok()) {")
    assert _DISCARD_PATTERN.search("        .filter_map(Result::ok)")
    assert not _DISCARD_PATTERN.search("for e in walker.filter_map(|e| e.map_err(log).ok()) {")

    # And the census must be non-empty: if it were empty the two ratchet arms would pass
    # vacuously no matter how broken the walks are.
    assert _census(), (
        "the census found ZERO error-discarding walks. Either every site was fixed (then "
        "empty KNOWN_DISCARD_SITES and delete this assertion) or the detector broke."
    )
