"""A RATCHET over the silent-filesystem-loss class in the Python sources.

THE CLASS: a loop walks filesystem entries and accumulates them into a collection that is
later reported as a result. One entry raises ``OSError`` (permission denied, a vanished file,
a disconnected share). A broad ``except`` swallows it and ``continue``s. The loop finishes,
the collection is SMALLER than the universe it claims to describe, and the command exits 0
with no marker. The caller -- almost always an AI agent -- concludes "no callers, safe to
delete" from a result set that was silently truncated.

That is the same defect the Rust-side ratchet pins for directory walks
(``test_native_walk_error_ratchet.py``, task #276). This file is its Python counterpart:
the codebase had a machine-checked census for one language and hand-enumeration for the
other, which is why the unreadable-path family (#276, #283, #284, #286, #288, #291) was
found one site at a time across a dozen separate PRs.

WHAT THIS DOES *NOT* CLAIM. A site in the census is not automatically a bug. Plenty of
best-effort loops are correct to skip an unreadable entry -- a heuristic seed list, an
optional cache probe. The census is the POPULATION that contains the defects, not the defect
list. Its job is the invariant: *the number of silent-loss sites never increases.* Auditing
a site and fixing it lowers the number; adding one without thinking about disclosure raises
it and turns CI red.

HOW A SITE GETS FIXED. Thread a ``_UnreadablePathFlag`` (see ``repo_map.py``) through the
loop, ``record(exc)`` in the handler, and have the caller disclose ``unreadable_paths``
alongside its result -- the shape #276 established and #767/#768/#769/#770 wired into
inventory, docs-coverage, the session snapshot and the validation plan. Then LOWER the count
here in the same PR.

House rule this implements: "model the class, don't enumerate the cases". Round N+1 finding
another instance of a defect family means the answer is an invariant, not another reviewer.

WHERE THAT RULE STOPS -- a near miss worth keeping (#292, 2026-07-26). Several audited-benign
sites share a shape: the handler only ASSIGNS a fallback and lets the loop continue, so nothing
is skipped (``resolved = candidate`` in the doctor PATH scans, ``_nearby_session_roots``). It is
tempting to teach the detector that shape and drop ~20 sites of noise in one edit.

Measuring the shape's distribution before encoding it showed why that would be a disaster:
``checkpoint_store``'s undo commit phase matched it too -- ``removed_bytes = None`` followed by an
``unlink()`` that destroys a file the revert can no longer restore. That was task #297, the most
severe defect this campaign found. A "benign fallback" rule would have excused it FOREVER, in the
exact file where it mattered most.

The lesson generalises: encode a shape only when it is *structurally* incapable of hiding a loss
(a handler that exits the process; one whose accumulator feeds a later ``raise``). "The handler
looks harmless" is not that. Whether a fallback is safe depends on what the loop DOES with the
fallback value afterwards, which is a semantic question this detector deliberately does not try
to answer. Audit those sites and record the verdict instead -- see CONTRACTS.md section 0.
"""

from __future__ import annotations

import ast
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
PY_SRC = REPO_ROOT / "src" / "tensor_grep"

# Filesystem calls whose failure means "this entry is missing from the result".
_FS_CALLS = frozenset(
    {
        "stat", "lstat", "open", "read_text", "read_bytes", "iterdir", "scandir",
        "walk", "resolve", "exists", "is_file", "is_dir", "is_symlink", "glob",
        "rglob", "listdir", "samefile",
    }
)  # fmt: skip

# A handler that does any of these has DISCLOSED the loss, so it is not silent.
_DISCLOSING_CALLS = frozenset({"record", "warning", "error", "exception", "critical"})

# Methods that accumulate into a collection the loop will hand back to a caller.
_ACCUMULATORS = frozenset({"append", "add", "update", "extend", "setdefault"})

# Exception types broad enough to swallow a filesystem failure. "BARE" is `except:`.
_BROAD_EXCEPTIONS = frozenset({"BARE", "OSError", "Exception", "EnvironmentError", "IOError"})

# MECHANICAL CENSUS -- generated by running this module's own detector, never from
# recollection. (A hand count of the unreadable-path family said "4 remaining repo_map
# sites"; the detector found 8 in that file alone. That gap is the whole reason this is
# machine-checked instead of prose.)
#
# file name -> number of silent-loss-in-an-accumulating-loop sites currently present.
#
# Started at 53 across 12 files. `docs_coverage.py` (2) and `inventory.py` (1) were audited and
# fixed in this same PR -- both were real gaps left by #767/#768, which wired the WALK but not the
# per-file read/stat loops -- so they are absent below rather than listed at zero.
KNOWN_SILENT_LOSS_SITES: dict[str, int] = {
    "main.py": 18,
    "checkpoint_store.py": 10,
    # AUDITED #292, all 8 accepted. The LSP legs (`_external_definitions` :15585,
    # `_external_references` :15693) skip a symbol whose LSP request failed, which lowers
    # `lsp_count` -- and `_provider_agreement` (:15258-15281) turns `native_count > lsp_count`
    # into `diverged` rather than a clean `lsp-only` proof. The loss reaches the caller through
    # that stamp; the comment at :15268 traces it to the v1.20.0 dogfood where `tg refs
    # --provider lsp` returned 2 of 14 marked authoritative. `:15713` is a different shape: a
    # failed `read_text` degrades the SNIPPET to the symbol name but still appends the reference,
    # so nothing is lost. CAVEAT: this verdict is from reading the code, not from a test that
    # observes the stamp flip -- proving it needs a live LSP server or heavy mocking.
    "repo_map.py": 8,
    # AUDITED #292, all 5 accepted. These gate the broad-scan REFUSAL heuristic, not an answer:
    # an OSError only means a huge scan is not refused, and the scan that follows discloses its
    # own incompleteness. main.py carries its own copies of the same family (#154/#158 siblings).
    # They stay pinned so a NEW one still trips the ratchet.
    "scan_guardrails.py": 5,
    # codemap.py drained to 0 by #296 (was 3): the tracked-file filter, the folder census and the
    # freshness digest now record into a post-walk accumulator that reaches `coverage.partial`.
    # Absent rather than pinned at 0 -- an entry at 0 and no entry are equivalent to both ratchet
    # arms, and the absence is what makes a re-introduction show up as a NEW file.
    # AUDITED #292, both session_store entries accepted, and they are two DIFFERENT non-defects:
    #   `_nearby_session_roots` :406 -- `resolved = candidate` is a FALLBACK, not a skip. The
    #     candidate stays in the loop; nothing is dropped at the handler.
    #   `_stale_changeset` :589 -- the #286 fix itself. It routes to a dedicated `indeterminate`
    #     bucket (plus `indeterminate_kinds`), which IS the disclosure: an unreadable file is
    #     deliberately left out of removed/changed/added rather than being called a deletion.
    # The second is a shape the detector structurally cannot see -- disclosure by routing to a
    # separate OUTPUT BUCKET, resolved outside the handler. Not worth widening the rule for:
    # "appends to a collection that is also returned" would match almost every real accumulator
    # and blind the detector. Recorded here instead, per CONTRACTS.md section 0.
    "session_store.py": 2,
    "ledger_store.py": 1,
    "runtime_paths.py": 1,
    "semantic_index.py": 1,
    "session_daemon.py": 1,
}


def _called_names(node: ast.AST) -> set[str]:
    """Every attribute/function name called anywhere under ``node``."""
    return {
        name
        for child in ast.walk(node)
        if isinstance(child, ast.Call)
        and (name := getattr(child.func, "attr", None) or getattr(child.func, "id", None))
    }


def _caught_names(handler: ast.ExceptHandler) -> set[str]:
    exc_type = handler.type
    if exc_type is None:
        return {"BARE"}
    parts = exc_type.elts if isinstance(exc_type, ast.Tuple) else [exc_type]
    return {getattr(p, "attr", None) or getattr(p, "id", None) or "?" for p in parts}


def _is_silent(handler: ast.ExceptHandler) -> bool:
    """True when the handler neither re-raises nor records the failure anywhere."""
    if any(isinstance(n, ast.Raise) for n in ast.walk(handler)):
        return False
    return not (_called_names(handler) & _DISCLOSING_CALLS)


def _silent_loss_lines(source: str) -> list[int]:
    """Line numbers of silent-loss sites in ``source``.

    A site is: a broad ``except`` with no disclosure, guarding a ``try`` body that touches the
    filesystem, nested inside a loop whose body accumulates into a collection or yields.
    """
    tree = ast.parse(source)
    found: list[int] = []
    for loop in ast.walk(tree):
        if not isinstance(loop, (ast.For, ast.While, ast.AsyncFor)):
            continue
        accumulates = bool(_called_names(loop) & _ACCUMULATORS) or any(
            isinstance(n, (ast.Yield, ast.YieldFrom)) for n in ast.walk(loop)
        )
        if not accumulates:
            continue
        for try_node in ast.walk(loop):
            if not isinstance(try_node, ast.Try):
                continue
            # Only the try BODY counts: an fs call inside the handler itself (a cleanup
            # probe) does not mean the guarded operation was a filesystem read.
            if not any(_called_names(stmt) & _FS_CALLS for stmt in try_node.body):
                continue
            found.extend(
                h.lineno
                for h in try_node.handlers
                if (_caught_names(h) & _BROAD_EXCEPTIONS) and _is_silent(h)
            )
    return found


def _census() -> dict[str, int]:
    """Count silent-loss sites per Python source file under ``src/tensor_grep``."""
    found: dict[str, int] = {}
    for path in sorted(PY_SRC.rglob("*.py")):
        hits = _silent_loss_lines(path.read_text(encoding="utf-8", errors="replace"))
        if hits:
            found[path.name] = len(hits)
    return found


@pytest.mark.skipif(not PY_SRC.is_dir(), reason="src/tensor_grep absent")
def test_no_new_files_start_losing_entries_silently() -> None:
    """A file not in the census must not introduce the idiom.

    This is the arm that bites on new code: a fresh ``except OSError: continue`` inside a
    result-building loop, in a file nobody has audited, is exactly how a command starts
    reporting success over a smaller universe.
    """
    unexpected = sorted(set(_census()) - set(KNOWN_SILENT_LOSS_SITES))
    assert not unexpected, (
        "these files newly swallow a filesystem error inside a loop that accumulates a "
        f"reported result, so a truncated result looks complete: {unexpected}. Thread an "
        "_UnreadablePathFlag through the loop and disclose `unreadable_paths` (see "
        "inventory.py / docs_coverage.py for the shape), or add the file to "
        "KNOWN_SILENT_LOSS_SITES with a reason if the loop genuinely makes no completeness "
        "claim."
    )


@pytest.mark.skipif(not PY_SRC.is_dir(), reason="src/tensor_grep absent")
def test_known_silent_loss_sites_never_grow() -> None:
    """Each audited file's count may FALL (a fix) but never RISE (a regression)."""
    census = _census()
    grew = {
        name: (census.get(name, 0), expected)
        for name, expected in KNOWN_SILENT_LOSS_SITES.items()
        if census.get(name, 0) > expected
    }
    assert not grew, (
        "the silent-loss count ROSE in these files (actual, allowed): "
        f"{grew}. Every added site is a new way for an incomplete result to report success."
    )

    shrank = {
        name: (census.get(name, 0), expected)
        for name, expected in KNOWN_SILENT_LOSS_SITES.items()
        if census.get(name, 0) < expected
    }
    assert not shrank, (
        "sites were FIXED but the ratchet was not lowered (actual, recorded): "
        f"{shrank}. Update KNOWN_SILENT_LOSS_SITES to the new counts so the ratchet keeps "
        "its teeth -- leaving it high would let a future regression slip back in unnoticed."
    )


@pytest.mark.skipif(not PY_SRC.is_dir(), reason="src/tensor_grep absent")
def test_the_detector_actually_discriminates() -> None:
    """ORACLE CHECK -- prove the detector bites before trusting either arm above.

    Without this, a detector that matched nothing would find zero sites everywhere, both
    ratchet arms would pass, and this file would silently certify a codebase it never
    inspected. A check that passes when the thing it guards is broken is not a check.
    (Verification-oracle family, form: the FIXTURE never applied.)

    The negative arms matter as much as the positive one: if a DISCLOSED handler still
    counted, fixing a site would not lower the number and the ratchet could never reach zero.
    """
    silent = """
for path in paths:
    try:
        out.append(path.stat().st_size)
    except OSError:
        continue
"""
    assert _silent_loss_lines(silent) == [5], "detector missed a plain silent-loss site"

    recorded = """
for path in paths:
    try:
        out.append(path.stat().st_size)
    except OSError as exc:
        unreadable.record(exc)
        continue
"""
    assert not _silent_loss_lines(recorded), "a handler that RECORDS must not count as silent"

    reraised = """
for path in paths:
    try:
        out.append(path.stat().st_size)
    except OSError as exc:
        raise BackendExecutionError(str(exc)) from exc
"""
    assert not _silent_loss_lines(reraised), "a handler that RE-RAISES must not count as silent"

    narrow = """
for path in paths:
    try:
        out.append(path.stat().st_size)
    except UnicodeDecodeError:
        continue
"""
    assert not _silent_loss_lines(narrow), (
        "a NARROW exception unrelated to filesystem availability must not count -- widening "
        "the detector to it would bury the real signal in noise"
    )

    no_claim = """
for path in paths:
    try:
        probe(path.stat())
    except OSError:
        continue
"""
    assert not _silent_loss_lines(no_claim), (
        "a loop that accumulates NOTHING makes no completeness claim and must not count"
    )

    # And the census must be non-empty: if it were, the two ratchet arms would pass
    # vacuously no matter how much the real code drops on the floor.
    assert _census(), (
        "the census found ZERO silent-loss sites. Either every site was fixed (then empty "
        "KNOWN_SILENT_LOSS_SITES and delete this assertion) or the detector broke."
    )
