"""A RATCHET over the silent-filesystem-loss class in the Python sources.

THE CLASS: a loop walks filesystem entries and accumulates them into a collection that is
later reported as a result. One entry raises ``OSError`` (permission denied, a vanished file,
a disconnected share). A broad ``except`` swallows it and ``continue``s. The loop finishes,
the collection is SMALLER than the universe it claims to describe, and the command exits 0
with no marker. The caller -- almost always an AI agent -- concludes "no callers, safe to
delete" from a result set that was silently truncated.

That is the same defect the Rust-side ratchet pins for directory walks
(``test_native_walk_error_ratchet.py``, task #276). This file is its Python counterpart:
the codebase had a machine-checked census for one language and hand-enumeration for the
other, which is why the unreadable-path family (#276, #283, #284, #286, #288, #291) was
found one site at a time across a dozen separate PRs.

WHAT THIS DOES *NOT* CLAIM. A site in the census is not automatically a bug. Plenty of
best-effort loops are correct to skip an unreadable entry -- a heuristic seed list, an
optional cache probe. The census is the POPULATION that contains the defects, not the defect
list. Its job is the invariant: *the number of silent-loss sites never increases.* Auditing
a site and fixing it lowers the number; adding one without thinking about disclosure raises
it and turns CI red.

HOW A SITE GETS FIXED. Thread a ``_UnreadablePathFlag`` (see ``repo_map.py``) through the
loop, ``record(exc)`` in the handler, and have the caller disclose ``unreadable_paths``
alongside its result -- the shape #276 established and #767/#768/#769/#770 wired into
inventory, docs-coverage, the session snapshot and the validation plan. Then LOWER the count
here in the same PR.

House rule this implements: "model the class, don't enumerate the cases". Round N+1 finding
another instance of a defect family means the answer is an invariant, not another reviewer.
"""

from __future__ import annotations

import ast
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
PY_SRC = REPO_ROOT / "src" / "tensor_grep"

# Filesystem calls whose failure means "this entry is missing from the result".
_FS_CALLS = frozenset(
    {
        "stat", "lstat", "open", "read_text", "read_bytes", "iterdir", "scandir",
        "walk", "resolve", "exists", "is_file", "is_dir", "is_symlink", "glob",
        "rglob", "listdir", "samefile",
    }
)  # fmt: skip

# A handler that does any of these has DISCLOSED the loss, so it is not silent.
_DISCLOSING_CALLS = frozenset({"record", "warning", "error", "exception", "critical"})

# Methods that accumulate into a collection the loop will hand back to a caller.
_ACCUMULATORS = frozenset({"append", "add", "update", "extend", "setdefault"})

# Exception types broad enough to swallow a filesystem failure. "BARE" is `except:`.
_BROAD_EXCEPTIONS = frozenset({"BARE", "OSError", "Exception", "EnvironmentError", "IOError"})

# MECHANICAL CENSUS -- generated by running this module's own detector, never from
# recollection. (A hand count of the unreadable-path family said "4 remaining repo_map
# sites"; the detector found 8 in that file alone. That gap is the whole reason this is
# machine-checked instead of prose.)
#
# file name -> number of silent-loss-in-an-accumulating-loop sites currently present.
#
# Started at 53 across 12 files. `docs_coverage.py` (2) and `inventory.py` (1) were audited and
# fixed in this same PR -- both were real gaps left by #767/#768, which wired the WALK but not the
# per-file read/stat loops -- so they are absent below rather than listed at zero.
KNOWN_SILENT_LOSS_SITES: dict[str, int] = {
    # 18 -> 17: `-f`/`--file` pattern-file reads already fail loud with exit 2 (the Backend
    # Fail-Closed Contract), but the handler calls `_exit_search_error` rather than raising
    # inline, so the detector read a terminating branch as silence.
    "main.py": 17,
    # 10 -> 6 by #297: three real fixes (the undo commit phase destroying a file whose bytes it
    # had failed to capture, so the revert could not restore it) plus one FALSE POSITIVE that the
    # detector no longer reports -- the undo pre-flight accumulates into `missing` and then raises
    # on it, which is disclosure, not loss.
    "checkpoint_store.py": 6,
    "repo_map.py": 8,
    "scan_guardrails.py": 5,
    "codemap.py": 3,
    "session_store.py": 2,
    "ledger_store.py": 1,
    "runtime_paths.py": 1,
    "semantic_index.py": 1,
    "session_daemon.py": 1,
}


def _called_names(node: ast.AST) -> set[str]:
    """Every attribute/function name called anywhere under ``node``."""
    return {
        name
        for child in ast.walk(node)
        if isinstance(child, ast.Call)
        and (name := getattr(child.func, "attr", None) or getattr(child.func, "id", None))
    }


def _caught_names(handler: ast.ExceptHandler) -> set[str]:
    exc_type = handler.type
    if exc_type is None:
        return {"BARE"}
    parts = exc_type.elts if isinstance(exc_type, ast.Tuple) else [exc_type]
    return {getattr(p, "attr", None) or getattr(p, "id", None) or "?" for p in parts}


def _terminates(handler: ast.ExceptHandler) -> bool:
    """True when the handler hands control to something that ends the command.

    ``sys.exit`` and this codebase's ``_exit_*`` helpers (e.g. ``_exit_search_error``) raise
    ``SystemExit`` internally, so nothing downstream ever sees a truncated result. The AST shows
    only a call, which read as silence and produced FALSE POSITIVES -- `-f` pattern-file reads
    (main.py) are the clearest case: they already fail loud with exit 2 per the Backend
    Fail-Closed Contract, and the census still counted them.
    """
    return any(
        name == "exit" or name.startswith("_exit_") or name.startswith("exit_")
        for name in _called_names(handler)
    )


def _raised_names(func: ast.AST) -> set[str]:
    """Names mentioned inside any ``raise`` in ``func``.

    Catches the accumulate-then-raise shape: the handler appends the failure to a list and the
    function raises on that list once the loop finishes (``checkpoint_store``'s undo pre-flight
    builds ``missing`` and then raises ``CheckpointCorruptError(..., missing_files=missing)``).
    Handler-local inspection cannot see that, so it counted a DISCLOSURE accumulator as loss.
    """
    names: set[str] = set()
    for node in ast.walk(func):
        if isinstance(node, ast.Raise):
            names |= {n.id for n in ast.walk(node) if isinstance(n, ast.Name)}
    return names


def _is_silent(handler: ast.ExceptHandler, raised_names: set[str]) -> bool:
    """True when the handler neither re-raises, records, terminates, nor feeds a later raise."""
    if any(isinstance(n, ast.Raise) for n in ast.walk(handler)):
        return False
    if _terminates(handler):
        return False
    if _called_names(handler) & _DISCLOSING_CALLS:
        return False
    # `missing.append(rel)` where the enclosing function later raises using `missing`.
    accumulated_into = {
        node.func.value.id
        for node in ast.walk(handler)
        if isinstance(node, ast.Call)
        and isinstance(node.func, ast.Attribute)
        and node.func.attr in _ACCUMULATORS
        and isinstance(node.func.value, ast.Name)
    }
    return not (accumulated_into & raised_names)


def _enclosing_raised_names(tree: ast.AST) -> dict[int, set[str]]:
    """Map each loop node's id() to the raise-names of the function that contains it."""
    mapping: dict[int, set[str]] = {}
    for func in ast.walk(tree):
        if not isinstance(func, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        raised = _raised_names(func)
        if not raised:
            continue
        for node in ast.walk(func):
            if isinstance(node, (ast.For, ast.While, ast.AsyncFor)):
                mapping[id(node)] = mapping.get(id(node), set()) | raised
    return mapping


def _silent_loss_lines(source: str) -> list[int]:
    """Line numbers of silent-loss sites in ``source``.

    A site is: a broad ``except`` that discloses nothing -- no re-raise, no log/record, no exit,
    and no accumulator the enclosing function later raises on -- guarding a ``try`` body that
    touches the filesystem, nested inside a loop whose body accumulates or yields.
    """
    tree = ast.parse(source)
    raised_by_loop = _enclosing_raised_names(tree)
    found: list[int] = []
    for loop in ast.walk(tree):
        if not isinstance(loop, (ast.For, ast.While, ast.AsyncFor)):
            continue
        accumulates = bool(_called_names(loop) & _ACCUMULATORS) or any(
            isinstance(n, (ast.Yield, ast.YieldFrom)) for n in ast.walk(loop)
        )
        if not accumulates:
            continue
        for try_node in ast.walk(loop):
            if not isinstance(try_node, ast.Try):
                continue
            # Only the try BODY counts: an fs call inside the handler itself (a cleanup
            # probe) does not mean the guarded operation was a filesystem read.
            if not any(_called_names(stmt) & _FS_CALLS for stmt in try_node.body):
                continue
            raised = raised_by_loop.get(id(loop), set())
            found.extend(
                h.lineno
                for h in try_node.handlers
                if (_caught_names(h) & _BROAD_EXCEPTIONS) and _is_silent(h, raised)
            )
    return found


def _census() -> dict[str, int]:
    """Count silent-loss sites per Python source file under ``src/tensor_grep``."""
    found: dict[str, int] = {}
    for path in sorted(PY_SRC.rglob("*.py")):
        hits = _silent_loss_lines(path.read_text(encoding="utf-8", errors="replace"))
        if hits:
            found[path.name] = len(hits)
    return found


@pytest.mark.skipif(not PY_SRC.is_dir(), reason="src/tensor_grep absent")
def test_no_new_files_start_losing_entries_silently() -> None:
    """A file not in the census must not introduce the idiom.

    This is the arm that bites on new code: a fresh ``except OSError: continue`` inside a
    result-building loop, in a file nobody has audited, is exactly how a command starts
    reporting success over a smaller universe.
    """
    unexpected = sorted(set(_census()) - set(KNOWN_SILENT_LOSS_SITES))
    assert not unexpected, (
        "these files newly swallow a filesystem error inside a loop that accumulates a "
        f"reported result, so a truncated result looks complete: {unexpected}. Thread an "
        "_UnreadablePathFlag through the loop and disclose `unreadable_paths` (see "
        "inventory.py / docs_coverage.py for the shape), or add the file to "
        "KNOWN_SILENT_LOSS_SITES with a reason if the loop genuinely makes no completeness "
        "claim."
    )


@pytest.mark.skipif(not PY_SRC.is_dir(), reason="src/tensor_grep absent")
def test_known_silent_loss_sites_never_grow() -> None:
    """Each audited file's count may FALL (a fix) but never RISE (a regression)."""
    census = _census()
    grew = {
        name: (census.get(name, 0), expected)
        for name, expected in KNOWN_SILENT_LOSS_SITES.items()
        if census.get(name, 0) > expected
    }
    assert not grew, (
        "the silent-loss count ROSE in these files (actual, allowed): "
        f"{grew}. Every added site is a new way for an incomplete result to report success."
    )

    shrank = {
        name: (census.get(name, 0), expected)
        for name, expected in KNOWN_SILENT_LOSS_SITES.items()
        if census.get(name, 0) < expected
    }
    assert not shrank, (
        "sites were FIXED but the ratchet was not lowered (actual, recorded): "
        f"{shrank}. Update KNOWN_SILENT_LOSS_SITES to the new counts so the ratchet keeps "
        "its teeth -- leaving it high would let a future regression slip back in unnoticed."
    )


@pytest.mark.skipif(not PY_SRC.is_dir(), reason="src/tensor_grep absent")
def test_the_detector_actually_discriminates() -> None:
    """ORACLE CHECK -- prove the detector bites before trusting either arm above.

    Without this, a detector that matched nothing would find zero sites everywhere, both
    ratchet arms would pass, and this file would silently certify a codebase it never
    inspected. A check that passes when the thing it guards is broken is not a check.
    (Verification-oracle family, form: the FIXTURE never applied.)

    The negative arms matter as much as the positive one: if a DISCLOSED handler still
    counted, fixing a site would not lower the number and the ratchet could never reach zero.
    """
    silent = """
for path in paths:
    try:
        out.append(path.stat().st_size)
    except OSError:
        continue
"""
    assert _silent_loss_lines(silent) == [5], "detector missed a plain silent-loss site"

    recorded = """
for path in paths:
    try:
        out.append(path.stat().st_size)
    except OSError as exc:
        unreadable.record(exc)
        continue
"""
    assert not _silent_loss_lines(recorded), "a handler that RECORDS must not count as silent"

    reraised = """
for path in paths:
    try:
        out.append(path.stat().st_size)
    except OSError as exc:
        raise BackendExecutionError(str(exc)) from exc
"""
    assert not _silent_loss_lines(reraised), "a handler that RE-RAISES must not count as silent"

    narrow = """
for path in paths:
    try:
        out.append(path.stat().st_size)
    except UnicodeDecodeError:
        continue
"""
    assert not _silent_loss_lines(narrow), (
        "a NARROW exception unrelated to filesystem availability must not count -- widening "
        "the detector to it would bury the real signal in noise"
    )

    no_claim = """
for path in paths:
    try:
        probe(path.stat())
    except OSError:
        continue
"""
    assert not _silent_loss_lines(no_claim), (
        "a loop that accumulates NOTHING makes no completeness claim and must not count"
    )

    # The two shapes the detector learned to forgive. Each needs BOTH arms: teaching it that
    # `_exit_*` and accumulate-then-raise are disclosure is exactly how a detector starts
    # under-reporting, so the near-miss must still count.
    terminates = """
for path in paths:
    try:
        out.append(path.stat().st_size)
    except OSError as exc:
        _exit_search_error("read_error", str(exc), json_mode=False, exit_code=2)
"""
    assert not _silent_loss_lines(terminates), (
        "a handler that EXITS the command cannot hand anyone a truncated result"
    )

    accumulate_then_raise = """
def check(paths):
    missing = []
    for path in paths:
        try:
            path.stat()
        except OSError:
            missing.append(path)
    if missing:
        raise CheckpointCorruptError("corrupt", missing_files=missing)
"""
    assert not _silent_loss_lines(accumulate_then_raise), (
        "appending to a list the function then RAISES on is disclosure, not loss"
    )

    accumulate_never_raised = """
def check(paths):
    missing = []
    kept = []
    for path in paths:
        try:
            kept.append(path.stat().st_size)
        except OSError:
            missing.append(path)
    if not kept:
        raise ValueError("empty")
    return kept
"""
    assert _silent_loss_lines(accumulate_never_raised), (
        "NEAR MISS: the function raises, but on `kept` -- `missing` is collected and thrown "
        "away, so the loss IS silent. If this stops counting, the raise-name check has "
        "widened into 'any raise anywhere excuses the whole function'."
    )

    # And the census must be non-empty: if it were, the two ratchet arms would pass
    # vacuously no matter how much the real code drops on the floor.
    assert _census(), (
        "the census found ZERO silent-loss sites. Either every site was fixed (then empty "
        "KNOWN_SILENT_LOSS_SITES and delete this assertion) or the detector broke."
    )
